project:
  type: website

website:
  title: "Ollie Ballinger"
  navbar:
    background: grey
    href: 'https://oballinger.github.io'


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



